sudo: required

services:
  - docker

# if we have multiple tests to build, we can specify it under the before_install section
before_install:
  - docker build -t abhinandkakkadi/react-test -f ./client/Dockerfile.dev ./client

# ll'y id we have multiple build for testing, we can specify it under this. In this case we only have test
# for react-app
script:
  - docker run -e CI=true abhinandkakkadi/react-test npm test

after_success:
  - docker build -t abhinandkakkadi/multi-client ./client
  - docker build -t abhinandkakkadi/multi-nginx ./nginx
  - docker build -t abhinandkakkadi/multi-server ./server
  - docker build -t abhinandkakkadi/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push abhinandkakkadi/multi-client
  - docker push abhinandkakkadi/multi-nginx
  - docker push abhinandkakkadi/multi-server
  - docker push abhinandkakkadi/multi-worker
